language: csharp
solution: "FluentVerification.sln"
install:
- nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
- xbuild FluentVerification.sln
- mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./FluentVerification.Tests/bin/Debug/FluentVerification.Tests.dll