language: csharp
solution: "FluentVerification.sln"
install:
- nuget restore FluentVerification.sln -Verbosity detailed
- nuget install NUnit.Runners -Version 3.6.1 -OutputDirectory testrunner
script:
- xbuild FluentVerification.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./FluentVerification.Tests/bin/Debug/FluentVerification.Tests.dll